### PR TITLE
Maintenance: Update ISAR and apply BB 2.0 changes

### PR DESCRIPTION
**Pull request by fmoessbauer**

### CODE REVIEW

**Review by chombourger — APPROVED** [review]
LGTM

**Comment by fmoessbauer** [comment]
Perfect. Just added one minor thing: explicitly set the branch for pycoral as bb 2.0 otherwise warns.

**Comment by chombourger** [comment]
> Perfect. Just added one minor thing: explicitly set the branch for pycoral as bb 2.0 otherwise warns.

Makes sense and looks good. Thanks

**Review by jan-kiszka — APPROVED** [review]
Looks good to me as well. Hope we can soon update meta-iot2050 as well so that we won't run into the situation of requiring later fixes without being bb2 ready yet.

**Pull request merged**
