### PR TITLE
recipes-python/python-absl: new upstream release (0.15.0-2)

### PR DESCRIPTION
**Pull request by fmoessbauer**
Signed-off-by: Cedric Hombourger <cedric.hombourger@siemens.com>
Acked-by: Felix Moessbauer <felix.moessbauer@siemens.com>

### CODE REVIEW

**Comment by fmoessbauer** [comment]
Unfortunately, the `0.15.0-1` tag has been removed on Debian salsa, breaking all builds that use the meta-coral layer prior to this patch. By that, we urgently have to merge this patch, cherry-picked from #22 .

**Comment by BaochengSu** [comment]
@fmoessbauer , do you know the exact commit-ish for the `0.15.0-1` tag?

**Comment by BaochengSu** [comment]
btw, is it possible that someday the `0.15.0-2` tag is removed as well? Could we use the commit-ish instead of the tag?

Another question is that, such kind of removal of the old tags is allowed in Debian?

**Comment by fmoessbauer** [comment]
> do you know the exact commit-ish for the 0.15.0-1 tag?

Just checked. It was 785d1ab505941df008608015d14d5b3ce6e30764

> btw, is it possible that someday the 0.15.0-2 tag is removed as well? Could we use the commit-ish instead of the tag?

Hopefully not. It looks like they re-wrote the whole git history of the project, so pinning the commit-ish would also not have worked.

> Another question is that, such kind of removal of the old tags is allowed in Debian?

AFAIK it is not common to rewrite the history on debian salsa (or remove tags), but salsa is not Debian. For Debian, just the things that are uploaded to the FTP servers are relevant, and there are very strict rules. But for salsa we basically have to hope for the best.

**Comment by BaochengSu** [comment]
> so pinning the commit-ish would also not have worked.

That could be an issue for our https://github.com/siemens/meta-iot2050, we are using the old tag, removal of it makes our 1.3.1 release not reproducible.

Could you ship me an old clone of the repo `https://salsa.debian.org/python-team/packages/python-absl`? I'd like to create the mirror just in case somebody need to reproduce the released image.

**Comment by fmoessbauer** [comment]
@BaochengSu I just sent you the mirror. But as just the packaging was changed, not the version of the sources, it is probably better to simply bump the version in meta-iot2050 as well (or transitively by bumping meta-coral).

IMO these tag changes are very rare, so if we really want to avoid them, we would have to fork or mirror all dependencies.

**Comment by BaochengSu** [comment]
> @BaochengSu I just sent you the mirror. But as just the packaging was changed, not the version of the sources, it is probably better to simply bump the version in meta-iot2050 as well (or transitively by bumping meta-coral).
> 

Thanks for your help, I've cleared all the local build hence I am not able to create such kind of mirror by myself. Yep, we will bump the version in the master branch, however, for the released v-tag, there is requirement to reproduce the binary with the locked package version, unfortunately, this removed tag is in the freezing list.

> IMO these tag changes are very rare, so if we really want to avoid them, we would have to fork or mirror all dependencies.

I think it's ok if this is rare case, forking or mirroring all dependencies is definitely not feasible.

**Pull request merged**
