### PR TITLE
feat: update tensorflow to 2.5.3

### LINKED ISSUE #13: Update tensorflow to 2.5.3
There is a new upstream release of TF 2.5, including a lot of patches and fixed CVEs (also to tflite).
The meta-coral layer currently packages 2.5.2. IMO we should update as soon as possible to 2.5.3.

Upstream changelog: https://github.com/tensorflow/tensorflow/releases/tag/v2.5.3

### PR DESCRIPTION
**Pull request by fmoessbauer**
closes: #13

Signed-off-by: Felix Moessbauer <felix.moessbauer@siemens.com>

### CODE REVIEW

**Comment by fmoessbauer** [comment]
@chombourger : Please note: I did only run simple tests on amd64 to see if the build is correct. Before merging, this has to be extensively tested.

**Review by chombourger — APPROVED** [review]

**Comment by chombourger** [comment]
> @chombourger : Please note: I did only run simple tests on amd64 to see if the build is correct. Before merging, this has to be extensively tested.

agreed. I can have our QA team run their tests and provide feedback

**Comment by jan-kiszka** [comment]
Works fine with meta-iot2050.

**Comment by fmoessbauer** [comment]
Rebased onto main.

**Comment by fmoessbauer** [comment]
@chombourger Any news from the QA? Shall we merge this?

**Comment by jan-kiszka** [comment]
For the sake of IOT2050, I would welcome to move forward with this.

**Comment by chombourger** [comment]
Same here. Our team hasn't completed their testing but we haven't seen any red herrings either

**Comment by fmoessbauer** [comment]
Thanks for the update. Then let's merge this, so meta-iot2050 can move forward.

**Pull request merged**
