### PR TITLE
replace curl-nss with curl-openssl in tensorflow

### PR DESCRIPTION
**Pull request by fmoessbauer**
Signed-off-by: Felix Moessbauer <felix.moessbauer@siemens.com>

### CODE REVIEW

**Comment by fmoessbauer** [comment]
Please manually check if the generated artifacts correctly work.

**Comment by jan-kiszka** [comment]
Reasoning is missing: libcurl4, the more recent default, is based on OpenSSL. NSS and GnuTLS flavors come as libcurl3 only. In addition, you cannot install libcurl4-*-dev packages in parallel right now, thus still cause headache with current Isar when also building packages (such as swupdate) that use libcurl4-openssl-dev.

Will test this soon.

**Comment by jan-kiszka** [comment]
Builds and still finds parrots on the IOT2050.

**Comment by jan-kiszka** [comment]
Any update here? I'd like to reference main from meta-iot2050, rather than a PR.

**Comment by fmoessbauer** [comment]
As I did not hear any objections yet, let's merge it to move our products forward.

**Pull request merged**
